version: '3'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: apscheduler-admin-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_TYPE=mysql
      - MYSQL_SERVER=db
      - MYSQL_USER=apscheduler
      - MYSQL_PASSWORD=apscheduler_password
      - MYSQL_DB=apscheduler_admin
      - MYSQL_PORT=3306
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=apscheduler_admin
      - POSTGRES_PORT=5432
      - SECRET_KEY=your-secret-key-for-jwt-please-change-in-production
      - FIRST_SUPERUSER=admin
      - FIRST_SUPERUSER_PASSWORD=admin
      - FIRST_SUPERUSER_EMAIL=admin@example.com
      - APSCHEDULER_JOBSTORES={"default":{"type":"sqlalchemy","url":"mysql+pymysql://apscheduler:apscheduler_password@db:3306/apscheduler_admin"}}
      - APSCHEDULER_EXECUTORS={"default":{"type":"threadpool","max_workers":20}}
      - APSCHEDULER_JOB_DEFAULTS={"coalesce":true,"max_instances":3,"misfire_grace_time":60}
    depends_on:
      - db
      - postgres
    networks:
      - apscheduler-network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: apscheduler-admin-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - apscheduler-network

  # MySQL 数据库
  db:
    image: mysql:8.0
    container_name: apscheduler-admin-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=apscheduler_admin
      - MYSQL_USER=apscheduler
      - MYSQL_PASSWORD=apscheduler_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - apscheduler-network

  # PostgreSQL 数据库
  postgres:
    image: postgres:14
    container_name: apscheduler-admin-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=apscheduler_admin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - apscheduler-network

networks:
  apscheduler-network:
    driver: bridge

volumes:
  mysql-data:
  postgres-data:
