version: '3'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: apscheduler-admin-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/apscheduler.db
      - SECRET_KEY=your-secret-key-for-jwt-please-change-in-production
    networks:
      - apscheduler-network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: apscheduler-admin-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - apscheduler-network

networks:
  apscheduler-network:
    driver: bridge
